# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.
"github" = ""
"rust" = ""
"jekyll" = ""
"youtube" = "磊"
"twitch" = "既"
"gmail" = ""
"google диск" = ""
"google" = ""
"bing" = ""
"duckduckgo" = ""
"searx" = ""
"discord" = ""
"spotify" = ""
"soundcloud" = ""
"nerd fonts" = ""
"firefox" = ""
"waterfox" = ""
"chrome" = ""
"vivaldi" = ""
"qutebrowser" = ""
"opera" = ""
"thunar" = ""
"pcmanfm" = ""
"caja" = ""
"nautilus" = ""
"dolphin" = ""
"ranger" = ""
"nnn" = ""
"xarchiver" = ""
"engrampa" = ""
"file-roller" = ""
"vimiv" = ""
"nvim" = ""
"vim" = ""
"imv" = ""
"imp" = ""
"mpv" = ""
"mplayer" = ""
"vlc" = ""
"musikcube" = ""
"nwg-look" = "漣"
"viber" = ""
"coffee" = ""
"ruby" = ""
"python" = ""
"python3" = ""
"alacritty" = ""
"kitty" = ""
"foot" = ""
"termit" = ""
"konsole" = ""
"terminal" = ""
"bash" = ""
"zsh" = ""
"fish" = ""
"ash" = ""
"ksh" = ""
[other]
fallback_icon = ""
deduplicate_icons = true
