"github" = ""
"rust" = ""
"jekyll" = ""
"youtube" = "磊"
"twitch" = "既"
"gmail" = ""
"google диск" = ""
"google" = ""
"bing" = ""
"duckduckgo" = ""
"searx" = ""
"discord" = ""
"spotify" = ""
"soundcloud" = ""
"nerd fonts" = ""
"waterfox" = ""
"thunar" = ""
"xarchiver" = ""
"vimiv" = ""
"nvim" = ""
"mpv" = ""
"musikcube" = ""
"nwg-look" = "漣"
"viber" = ""
"coffee" = ""
"node" = ""
"ruby" = ""
"python" = ""
"python3" = ""
"kitty" = ""
[other]
fallback_icon = ""
deduplicate_icons = true
